"""Write the classifier model card from the training summaries."""

from __future__ import annotations

import json
from pathlib import Path

from drdoom.config import get_settings

TITLE = "# Root-cause classifier"


def _confusion_table(classes: list[str], matrix: list[list[int]]) -> list[str]:
    header = "| actual \\ predicted | " + " | ".join(classes) + " |"
    divider = "|---|" + "---:|" * len(classes)
    rows = [
        f"| **{name}** | " + " | ".join(str(value) for value in row) + " |"
        for name, row in zip(classes, matrix, strict=True)
    ]
    return [header, divider, *rows]


def _reading_lines(summaries: list[dict]) -> list[str]:
    """State the comparisons the tables imply, generated from the numbers."""
    by_source = {summary["source"]: summary for summary in summaries}
    lines = ["## What the numbers say", ""]

    for summary in summaries:
        gain = summary["event_macro_f1"] - summary["window_macro_f1"]
        lines.append(
            f"- **{summary['source']}**: pooling windows into one verdict per incident moves "
            f"macro F1 from {summary['window_macro_f1']:.3f} to "
            f"{summary['event_macro_f1']:.3f} ({gain:+.3f}). Several windows voting on the "
            f"same incident cancel individual mistakes."
        )

    if "synthetic" in by_source and "smd" in by_source:
        synthetic = by_source["synthetic"]["event_macro_f1"]
        real = by_source["smd"]["event_macro_f1"]
        lines += [
            "",
            f"Synthetic scores {synthetic:.3f} against {real:.3f} on real telemetry. The gap is "
            "not evidence that the model is better at synthetic incidents; it is evidence that "
            "synthetic incidents are separable by construction. The generator picks a cause and "
            "writes its signature directly into the metrics, so a near-perfect score there "
            "measures the generator more than the classifier. The real number, on fewer and "
            "messier incidents, is the one to quote.",
        ]
    return [*lines, ""]


def render(summaries: list[dict]) -> str:
    lines = [
        TITLE,
        "",
        "Generated by `python -m drdoom.classify.train`.",
        "",
        "The classifier runs only after detection has flagged a window, so it is trained and",
        "scored on anomalous windows alone. Scores are reported per incident: window",
        "predictions are pooled by majority vote, because one verdict per incident is what an",
        "engineer acts on and because windows cut from the same outage are not independent",
        "observations.",
        "",
        "Cross-validation folds are grouped by incident. A random fold split would put",
        "overlapping slices of the same outage in both training and validation and report",
        "memorisation as skill.",
        "",
        "## Two label sets, never pooled",
        "",
        "**Synthetic** carries a true causal label on every incident, because the generator",
        "chose the cause before injecting it. This is where a claim about root-cause",
        "classification can actually be tested.",
        "",
        "**Real telemetry** does not. The Server Machine Dataset records which of its 38",
        "dimensions deviated during each incident but publishes no mapping from dimension to",
        'meaning, so calling a group of dimensions "memory" would be invention. Its labels',
        "here are signature archetypes: incidents clustered by the shape of their deviation,",
        "named for how much of the metric space they touch. That makes the real-data task",
        "subsystem-signature attribution rather than causal analysis, which is a weaker claim",
        "and the honest one.",
        "",
        "The archetype taxonomy is derived from the annotation file across all incidents, not",
        "from metric values, so it hands the model no signal it could read off its inputs.",
        "With 325 incidents in total there is not enough data to define the taxonomy on a",
        "subset and have it stay stable.",
        "",
    ]
    lines += _reading_lines(summaries)

    for summary in summaries:
        source = summary["source"]
        classes = summary["classes"]
        interval = summary["event_macro_f1_ci"]
        lines += [
            f"## {source}",
            "",
            f"- Classes: {', '.join(f'`{name}`' for name in classes)}",
            f"- Test incidents: {summary['test_events']} (from {summary['test_windows']} windows)",
            f"- **Event macro F1: {summary['event_macro_f1']:.3f}** "
            f"(95% CI [{interval[0]:.3f}, {interval[1]:.3f}])",
            f"- Event accuracy: {summary['event_accuracy']:.3f}",
            f"- Window macro F1: {summary['window_macro_f1']:.3f} (secondary)",
            f"- Grouped cross-validation macro F1 during tuning: {summary['best_cv_macro_f1']:.3f}",
            f"- Smallest class support in any split: "
            f"{summary['min_events_per_class_per_split']} incidents",
            "",
            "### Incidents per class in the test split",
            "",
            "| Class | Incidents |",
            "|---|---:|",
        ]
        lines += [f"| `{name}` | {count} |" for name, count in summary["events_per_class"].items()]
        lines += ["", "### Confusion matrix, per incident", ""]
        lines += _confusion_table(classes, summary["confusion"])
        lines += ["", "### Most informative features", "", "| Feature | Importance |", "|---|---:|"]
        lines += [
            f"| `{name}` | {value:.4f} |"
            for name, value in list(summary["feature_importance"].items())[:8]
        ]

        if "archetype_support" in summary:
            lines += [
                "",
                "### Archetype definitions",
                "",
                "| Archetype | Incidents | Dominant dimensions |",
                "|---|---:|---|",
            ]
            profiles = summary.get("archetype_profiles", {})
            for name, count in summary["archetype_support"].items():
                dims = profiles.get(name)
                shown = ", ".join(str(d) for d in dims) if dims else "n/a"
                lines.append(f"| `{name}` | {count} | {shown} |")
            lines += [
                "",
                "Dimensions are one-based indices into the 38 metric columns. The dataset",
                "publishes no names for them, so none are invented here.",
            ]
        lines.append("")

    return "\n".join(lines)


def write_card(summaries: list[dict], docs_root: Path | None = None) -> Path:
    docs = docs_root or get_settings().project_root / "docs"
    docs.mkdir(parents=True, exist_ok=True)
    path = docs / "classifier-card.md"
    path.write_text(render(summaries), encoding="utf-8")
    (docs / "classifier-summary.json").write_text(json.dumps(summaries, indent=2), encoding="utf-8")
    return path
