"""Write the dataset composition page from the manifests the build produced.

The page used to say it was generated while being typed by hand, which is the one claim a
results page cannot afford to get wrong. Every figure in the table now comes from a
``manifest.json`` written by ``drdoom.data.build``; the prose around it is fixed text.
"""

from __future__ import annotations

import json
from pathlib import Path

from drdoom.config import get_settings

SOURCES = ("smd", "synthetic")
STRATEGIES = ("time_based", "held_out_series")
SPLITS = ("train", "val", "test")

INTRO = """# Dataset composition

Generated by `python -m drdoom.data.build`. Every figure below comes from the
`manifest.json` written alongside each built split, not from hand counting.

## Sources

**Server Machine Dataset** is the primary benchmark: five weeks of telemetry from 28
production machines, 38 metrics each, with labelled anomaly intervals and an
interpretation file naming the deviating dimensions. It is real data, so detection
results measured on it are comparable against published work.

**Synthetic** is a controlled harness, not the headline benchmark. It exists for the
two things real data cannot supply: a known root cause per event, and a severity dial
that produces near-threshold incidents on demand. Results from the two sources are
always reported separately.

## Splits

`time_based` cuts each series chronologically and asks whether a future incident on a
known machine is detected. `held_out_series` assigns whole machines to one split and
asks whether the model transfers to a service it has never seen. Cuts never bisect an
incident: a boundary is nudged to the nearest normal timestep, so no event is counted
twice across two splits.
"""

OUTRO = """## Two things the table is saying

**The real training split holds zero events, by design.** The dataset separates an
anomaly-free period from a labelled one, and the detector is semi-supervised: it learns
normal behaviour and never sees an anomaly during training. A non-zero event count in
that row would mean the split was wrong.

**Events, not windows, are the unit that matters.** A single outage lasting hours
produces hundreds of overlapping windows. Counting those as independent observations
inflates the apparent sample size by an order of magnitude and makes a confidence
interval meaningless. Every window therefore carries the id of the event it overlaps,
and every downstream metric is grouped by that id.

Holding out whole machines at the usual 70/15/15 left five test machines and 43 events,
too few to separate detectors with confidence. The real dataset's held-out split trades
training machines for test events at 55/15/30; fifteen machines still supply roughly
380,000 normal timesteps, which is ample for the detector.

## Rebuilding

```bash
python -m drdoom.data.build              # every source and strategy
python -m drdoom.data.build --source smd --strategy held_out_series
```

The first run downloads roughly 460 MB and extracts it to `data/raw/`. Both `data/raw/`
and `data/processed/` are ignored by git and rebuild from the command above.
"""

HEADER = (
    "| Source | Strategy | Split | Series | Timesteps | Events | Windows "
    "| Anomalous windows | Median event |"
)
DIVIDER = "|---|---|---|---:|---:|---:|---:|---:|---:|"


def load_manifests(processed: Path | None = None) -> list[dict]:
    """Every manifest on disk, in the order the page lists them."""
    root = processed or get_settings().processed_data_dir
    manifests = []
    for source in SOURCES:
        for strategy in STRATEGIES:
            path = root / source / strategy / "manifest.json"
            if path.is_file():
                manifests.append(json.loads(path.read_text(encoding="utf-8")))
    return manifests


def _row(manifest: dict, split: str) -> str:
    counts = manifest["splits"][split]
    cells = [
        manifest["source"],
        manifest["strategy"],
        split,
        f"{counts['series']:,}",
        f"{counts['timesteps']:,}",
        f"{counts['events']:,}",
        f"{counts['windows']:,}",
        f"{counts['anomaly_window_rate']:.1%}",
        f"{counts['median_event_length']:,}",
    ]
    return "| " + " | ".join(cells) + " |"


def render(manifests: list[dict]) -> str:
    rows = [
        _row(manifest, split)
        for manifest in manifests
        for split in SPLITS
        if split in manifest["splits"]
    ]
    return "\n".join([INTRO, HEADER, DIVIDER, *rows, "", OUTRO])


def write_page(manifests: list[dict] | None = None, docs_root: Path | None = None) -> Path | None:
    """Render the page, or leave the existing one alone when there is nothing to render."""
    found = load_manifests() if manifests is None else manifests
    if not found:
        return None
    docs = docs_root or get_settings().project_root / "docs"
    docs.mkdir(parents=True, exist_ok=True)
    path = docs / "dataset.md"
    path.write_text(render(found), encoding="utf-8")
    return path
